name: fast # TODO

dependencies:
  - python=3.7
  - pytorch-gpu
  - torchvision
  - pip
  - pip:
      - gdown
      - numpy
      - pandas
      - opencv-python
      - matplotlib
      - --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html

# TODO specify version
# TODO dont forget pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html -U