name: fast
channels:
  - nvidia
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.9.0
  - torchvision=0.10.0
  - cudatoolkit=11.1
  - pip=21.1.2
  - pip:
      - gdown==3.13.0
      - numpy==1.21.0
      - pandas==1.2.5
      - opencv-python==4.5.2.54
      - matplotlib==3.4.2

# TODO specify version
